-- Adds Drop.visibility and Drop.scheduledFor (see Drop.prisma) for the
-- public/unlisted/private visibility picker and scheduled publishing.
-- Generated by `prisma migrate diff` against the schema (read-only, no
-- datasource connection) — not hand-written.
-- AlterTable
ALTER TABLE "drop" ADD COLUMN     "scheduledFor" TIMESTAMP(3),
ADD COLUMN     "visibility" TEXT NOT NULL DEFAULT 'public';

-- CreateIndex
CREATE INDEX "drop_status_scheduledFor_idx" ON "drop"("status", "scheduledFor");
