-- Finishes what 20260912120000_retire_personal_space (stale — it references
-- pre-rename table names "brand_space"/"space_post" that no longer exist;
-- the actual Brand Space -> Studio rename used "studio"/"drop" instead, and
-- happened out of band against the database) was trying to do: drop the
-- personal-Space columns User.prisma no longer declares.
--
-- No data migration needed here, unlike the old file — verified live
-- against the database first: 0 of 14 users have username, bio, or
-- backgroundImageKey set, and showFollowerCount is true (its default) for
-- all of them. Nothing to carry into a Studio row.
--
-- Generated by `prisma migrate diff` against the schema (read-only, no
-- datasource connection) — not hand-written.
-- AlterTable
ALTER TABLE "user" DROP COLUMN "backgroundImageKey",
DROP COLUMN "bio",
DROP COLUMN "showFollowerCount",
DROP COLUMN "username";
